### ISSUE TITLE
[Bug] Error running `/f invites`

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions_new#105]
**Describe the bug**

**Error log from console**
[error.txt](https://github.com/ToberoCat/ImprovedFactions_new/files/14817862/error.txt)

**To Reproduce**
1. run `/f invites`
2. See console

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Plugin: 2.0.3 dev
 - Server: 1.20.1 Paper build 196

**Additional context**

**Comment by ToberoCat** [comment]
Very weird kotlin to jvm code compilation error caused this issue. Fixed it. Will be shipped with the next guiengine / IF version
