### ISSUE TITLE
[Bug] 1.16.5 not loading the plugin

### ISSUE THREAD

**Issue by turtlez142** [ToberoCat/ImprovedFactions_new#11]
**Describe the bug**

trying to load 1.16.5 my server is running on java 11 and even on my computer its java 18 both out putting the same error

**Error log from console**
[16:28:32] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins/ImprovedFactionsV1.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: io/github/toberocat/MainIF has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Plugin: Improved Factions v1 pre release 5
 - Server: 1.16.5

**Additional context**

**Comment by ToberoCat** [comment]
Imporved factions needs java 16 or above to work, so your server has to upgrade to adoption java 16 or higher.
This site is quite simple to understand if you can't find a way to install java 18 correctly:
https://adoptium.net/de/temurin/releases/?version=18
Or just watch this tutorial:
https://www.youtube.com/watch?v=FVxKbAukRxk

When using a hoster, there is normally somewhere a section allowing you to change it

**Comment by jokbon** [comment]
java 17 supports the most plugins atm

**Comment by ToberoCat** [comment]
Yeah, IF will work with that too, as Java 16 is the minimum version

**Comment by Josh-65** [comment]
Shouldn't this be closed?
