### ISSUE TITLE
[Bug] Partical chunk boarder extention doesn't load

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions_new#13]
**Describe the bug**
I get the below error when turning on the server. The worlds havent changed since i downloaded the extention.

**Error log from console**
![unknown](https://user-images.githubusercontent.com/26977075/178584915-346a51fb-bd02-4e6d-929f-0c8b57092a72.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Plugin: 1.5
 - Paper 1.18.1 v216

**Comment by ToberoCat** [comment]
Have you had a multiverse world that got deleted?

**Comment by Josh-65** [comment]
At the time of installing no. Since then I have but the issue is the same both times

**Comment by ToberoCat** [comment]
So it is a problem with multiverse.

Can you send a screenshot of your ImprovedFactions/Data/Chunks folder?

**Comment by Josh-65** [comment]
![image](https://user-images.githubusercontent.com/26977075/182567029-e0baa9c8-4e1c-4221-ba11-2ed7c80de58a.png)

**Comment by ToberoCat** [comment]
So all these worlds still exist?

**Comment by Josh-65** [comment]
yes

**Comment by ToberoCat** [comment]
Okay then it looks like a issue that factions can't read claims for multiverse

**Comment by Josh-65** [comment]
This has been fixed with a redownload of the extention

**Comment by Josh-65** [comment]
So this is still an issue however can be fixed by going to plugins\ImprovedFactions\Data\Chunks > creating <worldname>.json > add `[ ]` in the file > restart the server.

**Comment by Josh65-2201** [comment]
Closing since this is from outdated build
