### ISSUE TITLE
[Bug] Lucky blocks data pack can bypass region protections

### ISSUE THREAD

**Issue by Josh-65** [ToberoCat/ImprovedFactions_new#24]
**Describe the bug**

No idea if it can be fixed but im using [this](https://www.planetminecraft.com/data-pack/super-furious-lucky-block-for-minecraft-1-14-4) data pack adding lucky blocks witch can destroy blocks in safezones and other players factions

**Error log from console**

**To Reproduce**

**Expected behavior**

Zones should be protected from the luckyblock affect like if a player were doing it

**Screenshots**

**Version (please complete the following information):**
 - Plugin: 1.5
 - Server: 1.18.2 paper 387

**Additional context**

**Comment by ToberoCat** [comment]
That is a issue because datapacks don't simulate a player block break / place and only use /setblock to change blocks. This isn't handled by the plugin, because it is a admin command anyway

**Comment by Josh-65** [comment]
Would it be possible to have a toggle on blocking those types of interaction with breaking other thing?
