### ISSUE TITLE
[Suggestion] Customizability In The GUI

### ISSUE THREAD

**Issue by Irkagiga** [ToberoCat/ImprovedFactions_new#29]
The Improved Factions plugin right now lay with a very good oportunity for it's developer and supporters. Many faction plugins are good for smps or medieval servers and are good at achieving that. This plugin now is decent mediocre plugin that doesn't give much but It has an excellent oportunity for it's developers. This neutrality is something we can use to make it a known and supported by many minecraft server owners in the future! I reperesent the customizablity feature!  This addition will make every server owner flook to this plugin! A faction plugin that can be customized to anything you want? That would be perfect! So long are the days of going to plugin to plugin finding a decent one for your server. This plugin will give people the ability to customize it for their server! Wanna add it for your 1940 nation server? Just change the lore, title and icons like different heads and items in the GUI! Wanna add it to an medieval server? Same process! This feature will make this plugin loved and wanted by many! A free plugin like this will make the factions community strong and sky rocket your own reputation! If you see this suggestion, please keep in mind this feature! Thank you for your time!

**Comment by ToberoCat** [comment]
Implemented in v2
