### ISSUE TITLE
[DevReport] Faction files are not created when running the /f create command

### ISSUE THREAD

**Issue by Josh-65** [ToberoCat/ImprovedFactions_new#37]
This creates an issue if the server crashed without being able to save as the factions are lost. Also make the in game `/f list` command not work until server restart.

**Comment by ToberoCat** [comment]
Okay, wasnÄt able to reproduce it. It maybe fixed, but I can't gurantee it

**Comment by Josh-65** [comment]
Still an issue for me in using Paper 1.18.2 build 387 with no other plugins. What did you test on?

**Comment by ToberoCat** [comment]
Tested it on paper for 1.18.2.

Are you getting errors in console when it should write the files?

The faction files normally get written when the all members are offline or the server restarts / stops

**Comment by Josh-65** [comment]
No they just dont show untill the server is restarted. The file should be made when it is created with ```/f create```

**Comment by ToberoCat** [comment]
Oh, I understand. It won't list because the file isn't found.
Yeah, I'll save them as soon as they get created
