### ISSUE TITLE
[DevReport] Factions names can have characters that are not allowed in files

### ISSUE THREAD

**Issue by Josh-65** [ToberoCat/ImprovedFactions_new#38]
It doesn't break the plugin entirely but makes a name less .json file which can cause issue with duplicate files and makes it hard to find the factions in external editor/readers.

These should always be blocked
![image](https://user-images.githubusercontent.com/26977075/187052672-eea908e1-da34-47dd-8814-10f3e90056e0.png)

**Comment by ToberoCat** [comment]
Will be fixed with next dev build. May break existing factions due to regex change

**Comment by Josh-65** [comment]
The characters are still allowed and still make the black name files.

**Comment by ToberoCat** [comment]
What? So this regex should remove these characters: [https://regex101.com/r/ZSBK7M/1](https://regex101.com/r/ZSBK7M/1)

**Comment by Josh-65** [comment]
Tested by putting the characters listed and it will accept it.
![image](https://user-images.githubusercontent.com/26977075/188182212-0663cb2c-1e1a-4888-a607-a56232a8beba.png)

**Comment by ToberoCat** [comment]
Yeah, for display names there are no limitations yet. Will put them i, as they seem to break everything
