### ISSUE TITLE
[DevReport] Command reordering suggestions

### ISSUE THREAD

**Issue by Josh-65** [ToberoCat/ImprovedFactions_new#51]
/f admin should contain `zones`, `editGUI` and `translateGUI`. Instead of having them in the root. this will remove the subcommand `gui` too. Maybe the `list` command too depend on if it meant to be seen by all users or admin

**Comment by ToberoCat** [comment]
Yeah, jokbon already told me that everything related to admin commands should be grouped in te admin section. I'll change the command hierarchy
