### ISSUE TITLE
[Suggestion] Faction prefix/suffix

### ISSUE THREAD

**Issue by AstRii69** [ToberoCat/ImprovedFactions_new#6]
Players in global chat should have a faction prefix or suffix so that other players can identify in which faction players are.

**Comment by ToberoCat** [comment]
Have you tried using placeholder API and a chat plugin supporting it?

The name property would be: %faction_name%

If you need help, you can ask someone on the ImprovedFactions discord. Someone will help for sure

**Comment by Josh-65** [comment]
Shouldn't this be closed since it supported?
