### ISSUE TITLE
[DevReport] Lots of warning every time doing /f

### ISSUE THREAD

**Issue by Josh-65** [ToberoCat/ImprovedFactions_new#63]
[temp.txt](https://github.com/ToberoCat/ImprovedFactions_new/files/10157541/temp.txt)

**Comment by ToberoCat** [comment]
Looks like it tries to decode an gui file or smth. Are you sure you removed the guis folder / removed the old files?

**Comment by ToberoCat** [comment]
Or at least it as an issue with your faction icon

**Comment by Josh-65** [comment]
Yeah deleting the old folder fixed it
