### ISSUE TITLE
[DevReport] .yml language format doesn't work with Geyser (Bedrock compatibility)

### ISSUE THREAD

**Issue by Josh-65** [ToberoCat/ImprovedFactions_new#70]
When using [Geyser](https://github.com/GeyserMC/Geyser) the language files aren't able to parse placeholders or hover text.

Java
![image](https://user-images.githubusercontent.com/26977075/221424989-7f38661d-561b-4e45-b95c-7c0fdd16349f.png)

Bedrock
![image](https://user-images.githubusercontent.com/26977075/221425003-1e59e741-11a8-49f5-a523-001de3188a60.png)

**Comment by ToberoCat** [comment]
Okay, I'll have to see why geyser doesn't do what I want it to do.
Do you maybe know of a way to check if a player is on java / bedrock? Maybe bedrock doesn't support things like the clickable text / hover text

**Comment by Josh-65** [comment]
I know bedrock doesn't support clickable or hover text but for other plugging they don't show the Information at all. Also don't think there is a way to know as the server will always see them as another java player.

**Comment by ToberoCat** [comment]
It must work... it's just basic string operations.
Did you get any errors or something that might give me a hint where i should look at?

**Comment by Josh-65** [comment]
No there wasnt anything in the console. Bedrocks using the en_gb (UK English) though

**Comment by Josh-65** [comment]
So I have found this is an issue with the language file formatting adding extra stuff and using the wrong placeholder. I guess the conversion to .yml didn't fully work. I will fix it for the other lines also.
