### ISSUE TITLE
[DevReport] GUI engine fails to load on second run

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions_new#73]
When loading for the first time it work fine after a restart it will fail to load. I've attached the error output of GUI engine

[error.txt](https://github.com/ToberoCat/ImprovedFactions_new/files/11424601/error.txt)

**Comment by ToberoCat** [comment]
Oh... looks like I forgot to remove a old gui file.
Delete manage-faction.gui (It's not a valid gui engine gui template)

**Comment by ToberoCat** [comment]
I'll have to work on more descriptive errors, not just this a big java exception

**Comment by Josh65-2201** [comment]
Merging with #75
