### ISSUE TITLE
[Bug] Quick and useful description

### ISSUE THREAD

**Issue by Piksel27** [ToberoCat/ImprovedFactions_new#74]
There is a bug with a DynMap extension
when i claim one chunk on dynmap it's on all of the map
![obraz_2023-05-10_151243358](https://github.com/ToberoCat/ImprovedFactions_new/assets/114017580/ce81cd40-94b7-410a-84b8-6d1036a2ebcc)

**Comment by ToberoCat** [comment]
It's a known bug that's gonna be fixed with a new version of the plugin.
Thanks for reporting though

**Comment by Piksel27** [comment]
ok
