### ISSUE TITLE
[DevReport] v2 stable has missing translation key

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions_new#77]
The pre generated file is missing the below
`base.exceptions.not-enough-permissions=<red>You don't have the required permission</red>`
`base.command.icon.invalid-icon=<red>Unknown id given</red>`

The languages folder should also be named `languages` not `i18n` as it currently is

**Comment by ToberoCat** [comment]
Missing properties iwll be added. The folder name will change to languages too
