### ISSUE TITLE
[DevReport] Permission nodes don't show in Luckperms

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions_new#79]
When installing the plugin for the first time no permission nodes will show in Luckperms. If I run the `create` command the create and info ones show but no others. It seems they only show as there used rather then loaded at startup.

**Comment by Josh65-2201** [comment]
This seem to also affect GUI Engine. I try using `/guiengine reload`

**Comment by ToberoCat** [comment]
The faction permissions will be added with the next stable build. GuiEngine will have the permissions added to with the next version, which might take a little bit longer
