### ISSUE TITLE
[Bug] Permission system not working for block interactions

### ISSUE THREAD

**Issue by 18O4** [ToberoCat/ImprovedFactions_new#8]
**Describe the bug**

Disabling interact permission for any rank using /f settings menu does not change anything. Players are still able to open chests and interact with doors.

**Error log from console**
I asked the server owner and they said there weren't any.

**To Reproduce**
1. Go to '/f settings'
2. Click on 'Manage ranks'
3. Click on 'Interact permission'
5. Disable for any or all ranks.

**Expected behavior**

Chest/door interaction event should be cancelled.

**Screenshots**

**Version (please complete the following information):**
 - Plugin: 1.5
 - Server: 1.16.5

**Additional context**

For some reason, it suddenly started working, I guess this can be closed then.

**Comment by ToberoCat** [comment]
Okay, will try to find why it wasn't for a moment
