### ISSUE TITLE
[DevReport] Commands that don't exist don't report unknown command message

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions_new#81]
## Description
Paper and sub forks of it normally report a unknown command message when the ran command doesn't exist, factions will not show anything.

## Steps to reproduce
1. Run command like `/f test`
2. See no paper unknown command message is given

## Log
No error shown in console/game

**Comment by ToberoCat** [comment]
Commands will now complain about commands not being found. Is going to be included in the next build
