### ISSUE TITLE
Factions keeps going into standby

### ISSUE THREAD

**Issue by Skytheredhead** [ToberoCat/ImprovedFactions_new#9]
Every once and a while, the plugin just goes into standby and I have to restart the server.

19.07 23:30:31 [Server] INFO M0RK69 issued server command: /f inviteaccept rulers
19.07 23:30:31 [Server]  java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.contains(Object)" because the return value of "io.github.toberocat.core.factions.members.FactionMemberManager.getInvitations()" is null
19.07 23:30:31 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.commands.factions.InviteAcceptSubCommand.lambda$CommandExecute$0(InviteAcceptSubCommand.java:35)
19.07 23:30:31 [Server]  at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
19.07 23:30:31 [Server]  at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1787)
19.07 23:30:31 [Server]  at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
19.07 23:30:31 [Server]  at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
19.07 23:30:31 [Server]  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
19.07 23:30:31 [Server]  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
19.07 23:30:31 [Server]  at java.base/java.util.stream.FindOps$FindTask.doLeaf(FindOps.java:319)
19.07 23:30:31 [Server]  at java.base/java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
19.07 23:30:31 [Server]  at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
19.07 23:30:31 [Server]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
19.07 23:30:31 [Server]  at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
19.07 23:30:31 [Server]  at java.base/java.util.stream.FindOps$FindOp.evaluateParallel(FindOps.java:160)
19.07 23:30:31 [Server]  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
19.07 23:30:31 [Server]  at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
19.07 23:30:31 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.find(AsyncTask.java:74)
19.07 23:30:31 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.commands.factions.InviteAcceptSubCommand.CommandExecute(InviteAcceptSubCommand.java:34)
19.07 23:30:31 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.command.SubCommand.lambda$CallSubCommand$2(SubCommand.java:171)
19.07 23:30:31 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask$1.run(AsyncTask.java:122)
19.07 23:30:31 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.lambda$runThread$5(AsyncTask.java:269)
19.07 23:30:31 [Server]  at java.base/java.lang.Thread.run(Thread.java:831)
19.07 23:30:31 [Server] ERROR §7[§e§lImprovedFactions§7] §cCannot invoke "java.util.ArrayList.contains(Object)" because the return value of "io.github.toberocat.core.factions.members.FactionMemberManager.getInvitations()" is null
19.07 23:30:31 [Server]  §7[§e§lImprovedFactions§7] ImprovedFactions put it self in standby. All commands will be disabled. Only simple claim protection is working
19.07 23:30:31 [Server] INFO §7[§e§lImprovedFactions§7] Please wait while the crash gets reported to the developer. Don't restart or shutdown the server
19.07 23:30:31 [Server] INFO [dynmap] Full render of map 'flat' of 'Skytheredhead' in progress - 50800 tiles rendered (116.90 msec/tile, 126.31 msec per render)
19.07 23:30:31 [Server]  §7[§e§lImprovedFactions§7] Unable to report occurred issue to github. PLease send it to the developer if you are connected to the wifi
19.07 23:30:31 [Server]  java.net.HttpRetryException: cannot retry due to server authentication, in streaming mode
19.07 23:30:31 [Server]  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1782)
19.07 23:30:31 [Server]  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
19.07 23:30:31 [Server]  at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
19.07 23:30:31 [Server]  at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
19.07 23:30:31 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:634)
19.07 23:30:31 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
19.07 23:30:31 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.service.IssueService.createIssue(IssueService.java:666)
19.07 23:30:31 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.service.IssueService.createIssue(IssueService.java:634)
19.07 23:30:31 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.gitreport.GitReport.reportIssue(GitReport.java:46)
19.07 23:30:31 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.Utility.lambda$except$0(Utility.java:182)
19.07 23:30:31 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask$3.run(AsyncTask.java:174)
19.07 23:30:31 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.lambda$runThread$5(AsyncTask.java:269)
19.07 23:30:31 [Server]  at java.base/java.lang.Thread.run(Thread.java:831)
19.07 23:30:31 [Server] INFO §7[§e§lImprovedFactions§7] Reported the issue
19.07 23:30:32 [Server] INFO woahh_andrew issued server command: /tpaccept
19.07 23:30:33 [Server] INFO [mcMMO] [config] Initializing config: itemweights.yml
19.07 23:30:33 [Server] INFO [mcMMO] [config] Loading config from disk: itemweights.yml
19.07 23:30:33 [Server] INFO [mcMMO] [config] Config initialized: itemweights.yml
19.07 23:30:33 [Server] INFO M0RK69 issued server command: /f inviteaccept rulers
19.07 23:30:33 [Server]  java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.contains(Object)" because the return value of "io.github.toberocat.core.factions.members.FactionMemberManager.getInvitations()" is null
19.07 23:30:33 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.commands.factions.InviteAcceptSubCommand.lambda$CommandExecute$0(InviteAcceptSubCommand.java:35)
19.07 23:30:33 [Server]  at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
19.07 23:30:33 [Server]  at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1787)
19.07 23:30:33 [Server]  at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
19.07 23:30:33 [Server]  at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
19.07 23:30:33 [Server]  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
19.07 23:30:33 [Server]  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
19.07 23:30:33 [Server]  at java.base/java.util.stream.FindOps$FindTask.doLeaf(FindOps.java:319)
19.07 23:30:33 [Server]  at java.base/java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
19.07 23:30:33 [Server]  at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
19.07 23:30:33 [Server]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
19.07 23:30:33 [Server]  at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
19.07 23:30:33 [Server]  at java.base/java.util.stream.FindOps$FindOp.evaluateParallel(FindOps.java:160)
19.07 23:30:33 [Server]  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
19.07 23:30:33 [Server]  at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
19.07 23:30:33 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.find(AsyncTask.java:74)
19.07 23:30:33 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.commands.factions.InviteAcceptSubCommand.CommandExecute(InviteAcceptSubCommand.java:34)
19.07 23:30:33 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.command.SubCommand.lambda$CallSubCommand$2(SubCommand.java:171)
19.07 23:30:33 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask$1.run(AsyncTask.java:122)
19.07 23:30:33 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.lambda$runThread$5(AsyncTask.java:269)
19.07 23:30:33 [Server]  at java.base/java.lang.Thread.run(Thread.java:831)
19.07 23:30:33 [Server] ERROR §7[§e§lImprovedFactions§7] §cCannot invoke "java.util.ArrayList.contains(Object)" because the return value of "io.github.toberocat.core.factions.members.FactionMemberManager.getInvitations()" is null
19.07 23:30:33 [Server] INFO §7[§e§lImprovedFactions§7] Please wait while the crash gets reported to the developer. Don't restart or shutdown the server
19.07 23:30:33 [Server]  §7[§e§lImprovedFactions§7] Unable to report occurred issue to github. PLease send it to the developer if you are connected to the wifi
19.07 23:30:33 [Server]  java.net.HttpRetryException: cannot retry due to server authentication, in streaming mode
19.07 23:30:33 [Server]  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1782)
19.07 23:30:33 [Server]  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
19.07 23:30:33 [Server]  at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
19.07 23:30:33 [Server]  at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
19.07 23:30:33 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:634)
19.07 23:30:33 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
19.07 23:30:33 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.service.IssueService.createIssue(IssueService.java:666)
19.07 23:30:33 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.service.IssueService.createIssue(IssueService.java:634)
19.07 23:30:33 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.gitreport.GitReport.reportIssue(GitReport.java:46)
19.07 23:30:33 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.Utility.lambda$except$0(Utility.java:182)
19.07 23:30:33 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask$3.run(AsyncTask.java:174)
19.07 23:30:33 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.lambda$runThread$5(AsyncTask.java:269)
19.07 23:30:33 [Server]  at java.base/java.lang.Thread.run(Thread.java:831)
19.07 23:30:33 [Server] INFO §7[§e§lImprovedFactions§7] Reported the issue
19.07 23:30:34 [Server] INFO M0RK69 issued server command: /f inviteaccept rulers
19.07 23:30:34 [Server]  java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.contains(Object)" because the return value of "io.github.toberocat.core.factions.members.FactionMemberManager.getInvitations()" is null
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.commands.factions.InviteAcceptSubCommand.lambda$CommandExecute$0(InviteAcceptSubCommand.java:35)
19.07 23:30:34 [Server]  at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
19.07 23:30:34 [Server]  at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1787)
19.07 23:30:34 [Server]  at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
19.07 23:30:34 [Server]  at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
19.07 23:30:34 [Server]  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
19.07 23:30:34 [Server]  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
19.07 23:30:34 [Server]  at java.base/java.util.stream.FindOps$FindTask.doLeaf(FindOps.java:319)
19.07 23:30:34 [Server]  at java.base/java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
19.07 23:30:34 [Server]  at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
19.07 23:30:34 [Server]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
19.07 23:30:34 [Server]  at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
19.07 23:30:34 [Server]  at java.base/java.util.stream.FindOps$FindOp.evaluateParallel(FindOps.java:160)
19.07 23:30:34 [Server]  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
19.07 23:30:34 [Server]  at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.find(AsyncTask.java:74)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.commands.factions.InviteAcceptSubCommand.CommandExecute(InviteAcceptSubCommand.java:34)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.command.SubCommand.lambda$CallSubCommand$2(SubCommand.java:171)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask$1.run(AsyncTask.java:122)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.lambda$runThread$5(AsyncTask.java:269)
19.07 23:30:34 [Server]  at java.base/java.lang.Thread.run(Thread.java:831)
19.07 23:30:34 [Server] ERROR §7[§e§lImprovedFactions§7] §cCannot invoke "java.util.ArrayList.contains(Object)" because the return value of "io.github.toberocat.core.factions.members.FactionMemberManager.getInvitations()" is null
19.07 23:30:34 [Server] INFO §7[§e§lImprovedFactions§7] Please wait while the crash gets reported to the developer. Don't restart or shutdown the server
19.07 23:30:34 [Server]  §7[§e§lImprovedFactions§7] Unable to report occurred issue to github. PLease send it to the developer if you are connected to the wifi
19.07 23:30:34 [Server]  java.net.HttpRetryException: cannot retry due to server authentication, in streaming mode
19.07 23:30:34 [Server]  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1782)
19.07 23:30:34 [Server]  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
19.07 23:30:34 [Server]  at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
19.07 23:30:34 [Server]  at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:634)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.service.IssueService.createIssue(IssueService.java:666)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.service.IssueService.createIssue(IssueService.java:634)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.gitreport.GitReport.reportIssue(GitReport.java:46)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.Utility.lambda$except$0(Utility.java:182)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask$3.run(AsyncTask.java:174)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.lambda$runThread$5(AsyncTask.java:269)
19.07 23:30:34 [Server]  at java.base/java.lang.Thread.run(Thread.java:831)
19.07 23:30:34 [Server] INFO §7[§e§lImprovedFactions§7] Reported the issue
19.07 23:30:34 [Server] INFO M0RK69 issued server command: /f inviteaccept rulers
19.07 23:30:34 [Server]  java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.contains(Object)" because the return value of "io.github.toberocat.core.factions.members.FactionMemberManager.getInvitations()" is null
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.commands.factions.InviteAcceptSubCommand.lambda$CommandExecute$0(InviteAcceptSubCommand.java:35)
19.07 23:30:34 [Server]  at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
19.07 23:30:34 [Server]  at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1787)
19.07 23:30:34 [Server]  at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
19.07 23:30:34 [Server]  at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
19.07 23:30:34 [Server]  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
19.07 23:30:34 [Server]  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
19.07 23:30:34 [Server]  at java.base/java.util.stream.FindOps$FindTask.doLeaf(FindOps.java:319)
19.07 23:30:34 [Server]  at java.base/java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
19.07 23:30:34 [Server]  at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
19.07 23:30:34 [Server]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
19.07 23:30:34 [Server]  at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
19.07 23:30:34 [Server]  at java.base/java.util.stream.FindOps$FindOp.evaluateParallel(FindOps.java:160)
19.07 23:30:34 [Server]  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
19.07 23:30:34 [Server]  at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.find(AsyncTask.java:74)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.commands.factions.InviteAcceptSubCommand.CommandExecute(InviteAcceptSubCommand.java:34)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.command.SubCommand.lambda$CallSubCommand$2(SubCommand.java:171)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask$1.run(AsyncTask.java:122)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.lambda$runThread$5(AsyncTask.java:269)
19.07 23:30:34 [Server]  at java.base/java.lang.Thread.run(Thread.java:831)
19.07 23:30:34 [Server] ERROR §7[§e§lImprovedFactions§7] §cCannot invoke "java.util.ArrayList.contains(Object)" because the return value of "io.github.toberocat.core.factions.members.FactionMemberManager.getInvitations()" is null
19.07 23:30:34 [Server] INFO §7[§e§lImprovedFactions§7] Please wait while the crash gets reported to the developer. Don't restart or shutdown the server
19.07 23:30:34 [Server]  §7[§e§lImprovedFactions§7] Unable to report occurred issue to github. PLease send it to the developer if you are connected to the wifi
19.07 23:30:34 [Server]  java.net.HttpRetryException: cannot retry due to server authentication, in streaming mode
19.07 23:30:34 [Server]  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1782)
19.07 23:30:34 [Server]  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
19.07 23:30:34 [Server]  at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
19.07 23:30:34 [Server]  at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:634)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.service.IssueService.createIssue(IssueService.java:666)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.service.IssueService.createIssue(IssueService.java:634)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.gitreport.GitReport.reportIssue(GitReport.java:46)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.Utility.lambda$except$0(Utility.java:182)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask$3.run(AsyncTask.java:174)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.lambda$runThread$5(AsyncTask.java:269)
19.07 23:30:34 [Server]  at java.base/java.lang.Thread.run(Thread.java:831)
19.07 23:30:34 [Server] INFO §7[§e§lImprovedFactions§7] Reported the issue
19.07 23:30:34 [Server] INFO M0RK69 issued server command: /f inviteaccept rulers
19.07 23:30:34 [Server]  java.lang.NullPointerException
19.07 23:30:34 [Server]  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
19.07 23:30:34 [Server]  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
19.07 23:30:34 [Server]  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
19.07 23:30:34 [Server]  at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
19.07 23:30:34 [Server]  at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
19.07 23:30:34 [Server]  at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:564)
19.07 23:30:34 [Server]  at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:591)
19.07 23:30:34 [Server]  at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:689)
19.07 23:30:34 [Server]  at java.base/java.util.stream.FindOps$FindOp.evaluateParallel(FindOps.java:160)
19.07 23:30:34 [Server]  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
19.07 23:30:34 [Server]  at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.find(AsyncTask.java:74)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.commands.factions.InviteAcceptSubCommand.CommandExecute(InviteAcceptSubCommand.java:34)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.command.SubCommand.lambda$CallSubCommand$2(SubCommand.java:171)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask$1.run(AsyncTask.java:122)
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.lambda$runThread$5(AsyncTask.java:269)
19.07 23:30:34 [Server]  at java.base/java.lang.Thread.run(Thread.java:831)
19.07 23:30:34 [Server]  Caused by: java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.contains(Object)" because the return value of "io.github.toberocat.core.factions.members.FactionMemberManager.getInvitations()" is null
19.07 23:30:34 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.commands.factions.InviteAcceptSubCommand.lambda$CommandExecute$0(InviteAcceptSubCommand.java:35)
19.07 23:30:34 [Server]  at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
19.07 23:30:34 [Server]  at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1787)
19.07 23:30:34 [Server]  at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
19.07 23:30:34 [Server]  at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
19.07 23:30:35 [Server]  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
19.07 23:30:35 [Server]  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
19.07 23:30:35 [Server]  at java.base/java.util.stream.FindOps$FindTask.doLeaf(FindOps.java:319)
19.07 23:30:35 [Server]  at java.base/java.util.stream.AbstractShortCircuitTask.compute(AbstractShortCircuitTask.java:115)
19.07 23:30:35 [Server]  at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
19.07 23:30:35 [Server]  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
19.07 23:30:35 [Server]  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176)
19.07 23:30:35 [Server]  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647)
19.07 23:30:35 [Server]  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614)
19.07 23:30:35 [Server]  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
19.07 23:30:35 [Server] ERROR §7[§e§lImprovedFactions§7] §cnull
19.07 23:30:35 [Server] INFO §7[§e§lImprovedFactions§7] Please wait while the crash gets reported to the developer. Don't restart or shutdown the server
19.07 23:30:35 [Server]  §7[§e§lImprovedFactions§7] Unable to report occurred issue to github. PLease send it to the developer if you are connected to the wifi
19.07 23:30:35 [Server]  java.net.HttpRetryException: cannot retry due to server authentication, in streaming mode
19.07 23:30:35 [Server]  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1782)
19.07 23:30:35 [Server]  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
19.07 23:30:35 [Server]  at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
19.07 23:30:35 [Server]  at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
19.07 23:30:35 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:634)
19.07 23:30:35 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
19.07 23:30:35 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.service.IssueService.createIssue(IssueService.java:666)
19.07 23:30:35 [Server]  at ImprovedFactionsV1.5.jar//org.eclipse.egit.github.core.service.IssueService.createIssue(IssueService.java:634)
19.07 23:30:35 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.gitreport.GitReport.reportIssue(GitReport.java:46)
19.07 23:30:35 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.Utility.lambda$except$0(Utility.java:182)
19.07 23:30:35 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask$3.run(AsyncTask.java:174)
19.07 23:30:35 [Server]  at ImprovedFactionsV1.5.jar//io.github.toberocat.core.utility.async.AsyncTask.lambda$runThread$5(AsyncTask.java:269)
19.07 23:30:35 [Server]  at java.base/java.lang.Thread.run(Thread.java:831)
19.07 23:30:35 [Server] INFO §7[§e§lImprovedFactions§7] Reported the issue

**To Reproduce**
1. Play on the server like usual
2. Wait some time (30m-24h)
3. You will see the error

I would expect this to not happen

**Screenshots**

**Version (please complete the following information):**
 - Plugin: ImprovedFactions V1.5
 - Server: Paper 1.19

**Comment by Josh-65** [comment]
Shouldn't this be closed since it fixed with 1.6+ and dev builds.

**Comment by ToberoCat** [comment]
Got fixed with the new version V1.6.1
