### ISSUE TITLE
[DevReport] Fails to load on start up

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions_new#92]
## Description
This happened when I restarted the server on the new rank update

## Logs
[error.log](https://github.com/ToberoCat/ImprovedFactions_new/files/12330547/error.log)

## Versions
Server: Paper 1.20.1 build 108
Plugin: 2.0.0 dev

**Comment by ToberoCat** [comment]
Oh, thanks for reminding me. This is a issue that it has when trying to migrate stuff. If I'm correct, you should be fine ignoring it until I've fixed it, but I'm not sure.

**Comment by Josh65-2201** [comment]
Unfortunately it completely disables the plugin for me.
